### ISSUE TITLE
RSI Edit is not showing animation frames

### ISSUE THREAD

**Issue by keronshb** [space-wizards/RSIEdit#39] opened 2022-08-01 22:54 UTC
![image](https://user-images.githubusercontent.com/54602815/182258830-fd719742-5166-42df-a6b8-d41b2ca3384a.png)

For example the mirror_shield here is animated. It was showing in the previous version.

**Comment by DrSmugleaf** [comment] 2022-10-04 14:13
Duplicate of https://github.com/space-wizards/RSIEdit/issues/16

**Closed by DrSmugleaf** 2022-10-04 14:13 UTC
